Models/Order.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PizzaOrderSystem2.Models
{
    public class Order
    {
        [Key]
        public int OrderID { get; set; }
        public int Quantity { get; set; }
        public string? AddedFlavors { get; set; }
        public double Contact_No { get; set; }
        public string? Address { get; set; }
        public double Total { get; set; }
        [ForeignKey("Pizza")]
        public int PizzaID { get; set; }
        public Pizza? Pizza { get; set; }
        }
}

Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PizzaOrderSystem2.Data;
using PizzaOrderSystem2.Models;

namespace PizzaOrderSystem2.Controllers
{
    public class OrdersController : Controller
    {
        private readonly PizzaOrderSystem2Context _context;
        public const string connectionString = "Server=(localdb)\\mssqllocaldb;Database=PizzaOrderSystem2Context-3ffb4c34-7333-465b-93c3-5bc9061c51b4;Trusted_Connection=True";
        protected void OnConfiguring(DbContextOptionsBuilder options)
        {
            options.UseSqlServer(connectionString);
        }
        public OrdersController(PizzaOrderSystem2Context context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var pizzaOrderSystem2Context = _context.Order.Include(o => o.Pizza);
            return View(await pizzaOrderSystem2Context.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.Pizza)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["PizzaID"] = new SelectList(_context.Pizza, "PizzaID", "PizzaID");
            return View();
        }
        //public async Task<IActionResult> UpdateStatus(int a)
        //{
        //    var stat = _context.Status;
        //    using (var dbconnect = _context)
        //    {

        //        Status? l = dbconnect.Status..Find(a);

        //        l.OrderStatus = "Order Placed";
        //        dbconnect.SaveChangesAsync();
        //        return View(stat);

        //    }
        //}

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderID,Quantity,AddedFlavors,Contact_No,Address,Total,PizzaID")] Order order)
        {
            var a = order.OrderID;
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                //await UpdateStatus(a);
                return RedirectToAction(nameof(Index)); 
            }
            ViewData["PizzaID"] = new SelectList(_context.Pizza, "PizzaID", "PizzaID", order.PizzaID);
            return View(order);
        }
  //      public IActionResult Small()
  //      {
  //          return View();
  //      }
		//public IActionResult Medium()
		//{
		//	return View();
		//}
		//public IActionResult Large()
		//{
		//	return View();
		//}

		// GET: Orders/Edit/5
		public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["PizzaID"] = new SelectList(_context.Pizza, "PizzaID", "PizzaID", order.PizzaID);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderID,Quantity,AddedFlavors,Contact_No,Address,Total,PizzaID")] Order order)
        {
            if (id != order.OrderID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PizzaID"] = new SelectList(_context.Pizza, "PizzaID", "PizzaID", order.PizzaID);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.Pizza)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Order == null)
            {
                return Problem("Entity set 'PizzaOrderSystem2Context.Order'  is null.");
            }
            var order = await _context.Order.FindAsync(id);
            if (order != null)
            {
                _context.Order.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return (_context.Order?.Any(e => e.OrderID == id)).GetValueOrDefault();
        }
    }
}

Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PizzaOrderSystem2.Data;
using PizzaOrderSystem2.Models;

namespace PizzaOrderSystem2.Controllers
{
    public class StatusController : Controller
    {
        private readonly PizzaOrderSystem2Context _context;
        

        public StatusController(PizzaOrderSystem2Context context)
        {
            _context = context;
        }

        // GET: Status
        public async Task<IActionResult> Index()
        {
            var pizzaOrderSystem2Context = _context.Status.Include(s => s.Order);
            return View(await pizzaOrderSystem2Context.ToListAsync());
        }

        // GET: Status/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Status == null)
            {
                return NotFound();
            }

            var status = await _context.Status
                .Include(s => s.Order)
                .FirstOrDefaultAsync(m => m.StatusID == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        // GET: Status/Create
        public IActionResult Create()
        {
            ViewData["OrderID"] = new SelectList(_context.Order, "OrderID", "OrderID");
            return View();
        }
        

        // POST: Status/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StatusID,OrderID,OrderStatus")] Status status)
        {
            
            if (ModelState.IsValid)
            {
                _context.Add(status);
                await _context.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderID"] = new SelectList(_context.Order, "OrderID", "OrderID", status.OrderID);
            return View(status);
        }

        // GET: Status/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Status == null)
            {
                return NotFound();
            }

            var status = await _context.Status.FindAsync(id);
            if (status == null)
            {
                return NotFound();
            }
            ViewData["OrderID"] = new SelectList(_context.Order, "OrderID", "OrderID", status.OrderID);
            return View(status);
        }

        // POST: Status/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StatusID,OrderID,OrderStatus")] Status status)
        {
            if (id != status.StatusID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(status);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StatusExists(status.StatusID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderID"] = new SelectList(_context.Order, "OrderID", "OrderID", status.OrderID);
            return View(status);
        }

        // GET: Status/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Status == null)
            {
                return NotFound();
            }

            var status = await _context.Status
                .Include(s => s.Order)
                .FirstOrDefaultAsync(m => m.StatusID == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        // POST: Status/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Status == null)
            {
                return Problem("Entity set 'PizzaOrderSystem2Context.Status'  is null.");
            }
            var status = await _context.Status.FindAsync(id);
            if (status != null)
            {
                _context.Status.Remove(status);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StatusExists(int id)
        {
          return (_context.Status?.Any(e => e.StatusID == id)).GetValueOrDefault();
        }
    }
}

Views/Orders/Create.cshtml
@model PizzaOrderSystem2.Models.Order

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<style>
    .navbar-expand-sm {
        background-color: crimson;
    }
</style>
<body style="background-color:burlywood;">
    </body>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">

                Check PizzaID for selecting a Pizza :

                <select class="form-control" id="name" name="name">
                    <option></option>
                    <option class="pizza" value="200"> 1.Margherita (S) - Veg</option>
                    <option class="pizza" value="300"> 2.Margherita (M) - Veg</option>
                    <option class="pizza" value="500"> 3.Margherita (L)- Veg</option>
                    <option class="pizza" value="250"> 4.Peppy Paneer (S)- Veg</option>
                    <option class="pizza" value="340"> 5.Peppy Paneer (M)- Veg</option>
                    <option class="pizza" value="630"> 6.Peppy Paneer (L)- Veg</option>
                    <option class="pizza" value="199"> 7.Veg Extravaganza (S)- Veg</option>
                    <option class="pizza" value="399"> 8.Veg Extravaganza (M)- Veg</option>
                    <option class="pizza" value="599"> 9. Veg Extravaganza (L)- Veg</option>
                    <option class="pizza" value="300"> 10.Veggie Paradise (S)- Veg</option>
                    <option class="pizza" value="450"> 11.Veggie Paradise (M)- Veg</option>
                    <option class="pizza" value="650"> 12.Veggie Paradise (L)- Veg</option>
                    <option class="pizza" value="229"> 13.Pepper Barbecue Chicken (S)- Non Veg</option>
                    <option class="pizza" value="449"> 14.Pepper Barbecue Chicken (M)- Non Veg</option>
                    <option class="pizza" value="649"> 15.Pepper Barbecue Chicken (L)- Non Veg</option>
                    <option class="pizza" value="299"> 17.Chicken Dominator (S)- Non Veg</option>
                    <option class="pizza" value="430"> 18.Chicken Dominator (M)- Non Veg</option>
                    <option class="pizza" value="600"> 19.Chicken Dominator (L)- Non Veg</option>
                    <option class="pizza" value="459"> 20.NonVeg Supreme (S)- Non Veg</option>
                    <option class="pizza" value="599"> 21.NonVeg Supreme (M)- Non Veg</option>
                    <option class="pizza" value="819"> 22. NonVeg Supreme (L)- Non Veg</option>

                </select>

            </div>
            
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" id="qnty" class="form-control" onkeyup="validate()" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">AddedFlavors
                @*<label asp-for="AddedFlavors" class="control-label"></label>
                <input asp-for="AddedFlavors" class="form-control" />
                <span asp-validation-for="AddedFlavors" class="text-danger"></span>*@
                <select asp-for="AddedFlavors" class="form-control" asp-items="ViewBag.AddedFlavors" name="AddedFlavors" required>
                    <option></option>
                    <option class="Extra">Extra Cheese</option>
                    <option class="Extra">Potato, sausage, pancetta/speck/bacon.</option>
                    <option class="Extra">Gorgonzola and mushroom</option>
                    <option class="Extra">Black olives, anchovies, capers</option>
                    <option class="Extra">Capers, anchovies, eggplant, capsicum</option>
                    <option class="Extra">Ricotta, cherry tomato, baby spinach </option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Contact_No" class="control-label"></label>
                <input asp-for="Contact_No" class="form-control" />
                <span asp-validation-for="Contact_No" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" id="tot" class="form-control" readonly/>
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PizzaID" class="control-label"></label>
                <select asp-for="PizzaID" class ="form-control" asp-items="ViewBag.PizzaID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" onclick="confirm('Confirm Order'),confirm('Your order has been confirmed')" class="btn btn-primary" />
                
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Status" asp-action="Index"></a> @*TRIAL*@
</div>
@*<button onclick="myFunction()">button
    </button>*@
@*<button id="Create">Order!</button>*@
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        //var ert=0;
        //var emd=0;
        
        $("#name").change(function () {
          var pizzza = $("#name option:selected").val();
          window.ert = parseInt(pizzza);
                  
        });
       
        //$(document).ready(function () { validate(); });
        function validate(){
        var quan=$("#qnty").val();
        var emd=parseInt(quan);
        
            var total = ert * emd;
            $('#tot').val(total);
        }

        //function myFunction() {
        //    alert("order has been placed!");
        //}
        //const button = document.getElementById('Create');
        //button.addEventListener('click', () => {
        //    alert('Button clicked!');
        //});


    </script>
}

Views/Orders/Delete.cshtml
@model PizzaOrderSystem2.Models.Order

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>
<style>
    .navbar-expand-sm {
        background-color: crimson;
    }
</style>
<body style="background-color:burlywood;">
</body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AddedFlavors)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AddedFlavors)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact_No)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact_No)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pizza)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pizza.PizzaID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderID" />
        <input type="submit" value="Cancel" onclick="confirm('Do you want to cancel your order?'),confirm('Your order has been cancelled')" class="btn btn-danger" /> |
        <a asp-controller="Status" asp-action="Index"></a> @*TRIAL*@
    </form>
</div>

Views/Orders/Details.cshtml
@model PizzaOrderSystem2.Models.Order

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<style>
    .navbar-expand-sm {
        background-color: crimson;
    }
</style>
<body style="background-color:burlywood;">
</body>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AddedFlavors)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AddedFlavors)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact_No)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact_No)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pizza)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pizza.PizzaID)
        </dd>
    </dl>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model?.OrderID">Edit</a>*@ |
    <a asp-action="Index">Back to List</a>
</div>

Views/Orders/Edit.cshtml
@model PizzaOrderSystem2.Models.Order

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<style>
    .navbar-expand-sm {
        background-color: crimson;
    }
</style>
<body style="background-color:burlywood;">
</body>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderID" />
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddedFlavors" class="control-label"></label>
                <input asp-for="AddedFlavors" class="form-control" />
                <span asp-validation-for="AddedFlavors" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact_No" class="control-label"></label>
                <input asp-for="Contact_No" class="form-control" />
                <span asp-validation-for="Contact_No" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PizzaID" class="control-label"></label>
                <select asp-for="PizzaID" class="form-control" asp-items="ViewBag.PizzaID"></select>
                <span asp-validation-for="PizzaID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Orders/Index.cshtml
@model IEnumerable<PizzaOrderSystem2.Models.Order>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<style>
    .navbar-expand-sm {
        background-color: crimson;
    }
</style>
<body style="background-color:burlywood;">
</body>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pizza.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PizzaID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AddedFlavors)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contact_No)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pizza.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PizzaID)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddedFlavors)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contact_No)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pizza.PizzaID)
            </td>
            <td>
               @* <a asp-action="Edit" asp-route-id="@item.OrderID">Edit</a> |*@
                <a asp-action="Details" asp-route-id="@item.OrderID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.OrderID">Cancel</a>
            </td>
        </tr>
}
    </tbody>
</table>